name: development workflow
on:
  push:
    branches:
      - dev

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - name: linting
        run: npm run lint
